### ISSUE TITLE
fromString method for WindIcon

### ISSUE THREAD

**Issue by HannesGitH** [worldturtlemedia/weather_icons#29]
similar to `WeatherIcons.fromString()` but for `WindIcon`

**Comment by jordond** [comment]
`WeatherIcons.fromString()` returns an `IconData` that can then be then be passed to an `Icon` or `BoxedIcon`. 

To implement a `WindIcon.toString()` it would have to return a `WindIcon` instead of `IconData` as the icon data is the same for a wind icon, it just needs to be rotated by its degree value.

If that's what you're looking for it could be implemented.

**Comment by HannesGitH** [comment]
Yeah I was looking for a way to always get IconData for any string that the web version offers

But I found a workaround so this can be closed if no one else is interested in this functionality

But thanks for explaining :)
